import '../../../templates/ucorpora/styles/style'
import '../../../templates/ucorpora/styles/flexslider'
import '../../../templates/ucorpora/js/functions'
import '../../../templates/ucorpora/js/jquery.flexslider'
import '../../../templates/ucorpora/images/logo-header.png'