---
  - name: Install Postgresql
    become: yes
    apt:
      pkg:
        - postgresql
        - postgresql-contrib
        - libpq-dev
      update_cache: true
      state: present
  - name: Create database user
    become: yes
    become_user: postgres
    postgresql_user: 
      user: postgres 
      password: fuitter
  - name: Create database
    become: yes
    become_user: postgres
    postgresql_db: 
      name: fuitter 
      owner: postgres
